# Generated by Django 3.2.23 on 2023-12-13 04:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('spdiary', '0003_auto_20231212_1437'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diary',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='todo',
            name='title',
        ),
        migrations.AddField(
            model_name='todo',
            name='time',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='作成日'),
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
