# Generated by Django 3.2.23 on 2023-12-16 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spdiary', '0006_auto_20231216_1755'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diary',
            name='relation',
        ),
        migrations.AlterField(
            model_name='diary',
            name='tag',
            field=models.ManyToManyField(to='spdiary.Tag'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
