# Generated by Django 3.2.23 on 2023-12-12 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spdiary', '0002_diary'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='diary',
            name='tag',
            field=models.ManyToManyField(to='spdiary.Tag'),
        ),
    ]
