# Generated by Django 3.2.23 on 2023-12-21 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spdiary', '0009_diary_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='題名')),
                ('image', models.ImageField(upload_to='img/upload')),
            ],
        ),
        migrations.RemoveField(
            model_name='diary',
            name='image',
        ),
        migrations.AlterField(
            model_name='diary',
            name='text',
            field=models.CharField(max_length=250, verbose_name='本文'),
        ),
    ]
