# Generated by Django 3.2.23 on 2023-12-29 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spdiary', '0010_auto_20231221_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='memo',
            field=models.TextField(max_length=255, verbose_name='メモ'),
        ),
    ]
