# Generated by Django 3.2.23 on 2024-01-07 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spdiary', '0011_alter_todo_memo'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='status',
            field=models.IntegerField(choices=[(1, '未完了'), (2, '作業中'), (3, '完了')], default=1),
        ),
        migrations.AlterField(
            model_name='diary',
            name='text',
            field=models.CharField(max_length=250, verbose_name='日記'),
        ),
    ]
