# Generated by Django 3.2.23 on 2024-01-08 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spdiary', '0012_auto_20240107_2317'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='status',
        ),
    ]
