# Generated by Django 3.2.23 on 2024-01-13 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spdiary', '0013_remove_todo_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='memo',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='メモ'),
        ),
    ]
