# Generated by Django 3.2.23 on 2024-01-16 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spdiary', '0014_image_memo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diary',
            name='tagname',
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=50, verbose_name='タグ'),
        ),
    ]
