# Generated by Django 3.2.23 on 2024-01-16 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spdiary', '0015_auto_20240116_1012'),
    ]

    operations = [
        migrations.AddField(
            model_name='diary',
            name='tagname',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='タグ'),
        ),
    ]
