# Generated by Django 3.2.23 on 2024-01-16 02:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('spdiary', '0016_diary_tagname'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='today',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='作成日'),
        ),
    ]
