# Generated by Django 3.2.23 on 2024-01-17 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spdiary', '0017_image_today'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='text',
            field=models.TextField(max_length=255, verbose_name='日記'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='memo',
            field=models.CharField(max_length=255, verbose_name='メモ'),
        ),
    ]
