# Generated by Django 3.2.23 on 2024-01-18 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spdiary', '0019_todo_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='author',
            new_name='user',
        ),
    ]
